### ISSUE TITLE
Move repository to D3 Organization?

### ISSUE THREAD

**Issue by curran** [curran/d3-component#21]
Proposal: move this repository from [github.com/curran/d3-component](https://github.com/curran/d3-component) to [github.com/d3/d3-component](https://github.com/d3/d3-component).

**Comment by curran** [comment]
I'd like to start a conversation with D3 organization members on whether a module like d3-component  would be welcome under github.com/d3 .

@mbostock @biovisualize @jasondavies @jheer @justincormack @RichMorin @NelsonMinar @n8agrin @larskotthoff @syntagmatic @tmcw @xaranke

What do you think? Does it solve a common need? Is it a reasonable idea? Is the abstraction too heavy or high level to fit within the philosophy of D3?

It looks like it's starting to take off, judging by the [npm downloads](https://www.npmjs.com/package/d3-component), so I'd love to hear any feedback. Ultimately I'd like to see this module find a home at github.com/d3/d3-component, but only it it's welcome by the community.

![image](https://cloud.githubusercontent.com/assets/68416/24295498/fcfd0168-10c0-11e7-8934-60fa2aac02f6.png)

For more context on the purpose of this module, see https://github.com/curran/d3-component/issues/43

**Comment by DougManuel** [comment]
What about merging with [https://github.com/gka/d3-jetpack](https://github.com/gka/d3-jetpack)?

**Comment by curran** [comment]
What would be the benefit?

Closing this issue as it seems not realistic/relevant anymore.
