### ISSUE TITLE
Upgrade examples to v3

### ISSUE THREAD

**Issue by curran** [curran/d3-component#67]
The examples should be updated to the [v3 API](https://github.com/curran/d3-component/issues/70).

Bl.ocks belonging to @curran

 * [x] [Hello d3-component](http://bl.ocks.org/curran/c3d9783e641636479fa8e07a480e7233)
 * [x] [Posts with d3-component](https://bl.ocks.org/curran/fc8f6989901628e2e79d6374849453ed)
 * [x] [Spinner with d3-component](https://bl.ocks.org/curran/685fa8300650c4324d571c6b0ecc55de)
 * [x] [Stopwatch](https://bl.ocks.org/curran/593ffae30c42789a9af36f08c983867e)
 * [x] [Counter](https://bl.ocks.org/curran/acde35df0c7939ff97740b4f9800258e)
 * [x] [Todos](https://bl.ocks.org/curran/d8639546697c7ae3ab46c2544683d53a)
 * [x] [Scatter Plot with Menus](http://bl.ocks.org/curran/8c131a74b85d0bb0246233de2cff3f52)
 * [x] [Clock](https://bl.ocks.org/curran/28047fcfeb11cc0c66d10e7f30e1fe22)
 * [x] [Airport Clocks](https://bl.ocks.org/curran/598e90fe0dcab73030dbecc38fb6e725)
 * [ ] [example-viewer](https://github.com/curran/example-viewer)

Bl.ocks belonging to @micahstubbs 

 * [x] [posts with d3-component | hipster ipsum](https://bl.ocks.org/micahstubbs/23a43e0236d235fe52855dc6aecd74a0)
 * [x] [spinner with d3-component | es2015](https://bl.ocks.org/micahstubbs/0e2b63921f5642f0f65f51e27cccd02f)
 * [x] [stopwatch with d3-component | es2015](https://bl.ocks.org/micahstubbs/8e94f74c7d0a5dec710330574781fda0)
 * [x] [counter with d3-component | es2015](https://bl.ocks.org/micahstubbs/04df008db0b12474a726a7986d73ad14)
 * [x] [scatterplot menus with d3-component | es2015](http://bl.ocks.org/micahstubbs/9180020ff8265eade016a82ba54db26b)
 * [x] [scatterplot menus with d3-component | radius select](http://bl.ocks.org/micahstubbs/b097f9d0999848ee70b74b36ce30cbb8)

**Comment by micahstubbs** [comment]
nice, thanks for making an issue linking all these together @curran

**Comment by micahstubbs** [comment]
hope to do this soon  😅

**Comment by micahstubbs** [comment]
@curran just updated all of my examples 😄

**Comment by curran** [comment]
Sweet. Thanks a ton!
