### ISSUE TITLE
document tests

### ISSUE THREAD

**Issue by micahstubbs** [curran/d3-component#72]
would be nice to document how to run the tests

![screen shot 2017-03-20 at 3 22 42 am](https://cloud.githubusercontent.com/assets/2119400/24095923/87820d90-0d1c-11e7-8cc3-fd16722c4adb.png)

**Comment by curran** [comment]
`npm test`

My thought was the script in `package.json` would be a good enough hint. Maybe something should be added to the README?

**Comment by curran** [comment]
Opted to introduce a new `README.md` under `tests`, so as to provide instructions for those looking for it, but not pollute the main README.

@micahstubbs Could you please review #74?
