### ISSUE TITLE
document eslint

### ISSUE THREAD

**Issue by curran** [curran/d3-component#76]
@micahstubbs How are you running the ESLint added in #73 ?

I tried `./node_modules/.bin/eslint .` and saw the following:

```
Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-jsx-a11y". This can happen for a couple different reasons:
```

Perhaps it would be nice to add a "lint" script to `package.json`, so as not to depend on a global `eslint` installation nor require developers to use `./node_modules/.bin` ?

**Comment by curran** [comment]
Also just noticed this warning:

```
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-jsx-a11y@^1.2.0 but none was installed.
npm WARN eslint-config-airbnb@9.0.1 requires a peer of eslint-plugin-react@^5.0.1 but none was installed.
```

Gathering my thoughts on potential tasks here:

EITHER

 * [ ] Add `eslint-plugin-jsx-a11y` as a devDependency
 * [ ] Add `eslint-plugin-react` as a devDependency

OR

 * [ ] Remove the following devDependencies, and make linting more of a personal/optional activity

```
    "eslint": "^2.9.0",
    "eslint-config-airbnb": "^9.0.1",
    "eslint-plugin-import": "^1.10.2",
```

I'm not sure if it's better to have +5 devDependencies just for linting, or to have fewer devDependencies for the sake of simplicity.

**Comment by micahstubbs** [comment]
@curran think those warnings can be safely ignored so long as the project doesn't contain react or jsx

**Comment by micahstubbs** [comment]
@curran linting of course is up to you. many of the eslint rules are about correctness rather than code style, so help prevent errors and ambiguous code that could lead to a human error later.

**Comment by micahstubbs** [comment]
@curran to run eslint, say `eslint --fix component.js`

**Comment by micahstubbs** [comment]
an npm script like this is a common way to make linting easier to do:
`"lint": "eslint index.js src --fix"`
as used at this other project: https://github.com/micahstubbs/drift/blob/master/package.json#L9

**Comment by curran** [comment]
@micahstubbs ESLint is actually not running due to missing the `eslint-plugin-jsx-a11y` package and another React-related one.

I did some digging and discovered the package [airbnb-base](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base), which is the subset of the Airbnb ESLint config that applies to JavaScript *only*, not JSX, which is exactly what we need here. Using this, these extraneous React-related packages will not be necessary.

Adopting `airbnb-base` went fairly well, and it simplified the customizations you had introduced in `.eslintrc`. If you have time, would you be able to review these changes in #78?

**Comment by micahstubbs** [comment]
nice, will have a look now.  thanks for teaching me about `airbnb-base` 😄

**Comment by micahstubbs** [comment]
made some comments on https://github.com/curran/d3-component/pull/78

looks like a nice improvement 👍
